language: go
go:
  - 1.11.x
  - 1.13.x
  - master

env:
  - GO111MODULE=on

script:
  - go get -v -t -d ./...
  - go build -v ./...
  - go test -v ./...
  - go build
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
